### ISSUE TITLE
No GUI opening

### ISSUE THREAD

**Issue by folence** [BakaBox/myManga#18]
Hi, i just installed this but i cant get the GUI to open, it says the program is open in task manager, so yeah.

Here is the log.
========== 22.09.2015 ==========
========== MESSAGE ==========
Unable to load 'AFTVNetwork.mymanga.dll'
========== STACK TRACE ==========
   at Core.DLL.DLL_Loader`1.LoadDLL(String DLLPath)
   at Core.DLL.DLL_Loader`1.LoadDirectory(String DirectoryPath, String Filter, SearchOption DirectorySearchOption)
   at Core.DLL.DLL_Manager`2.LoadDLL(String DLLPath, String Filter, SearchOption DirectorySearchOption)
   at myManga_App.App.App_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
========== TARGET SITE ==========
T[] LoadDLL(System.String)

========== MESSAGE ==========
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
========== STACK TRACE ==========
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Core.DLL.DLL_Loader`1.LoadDLL(String DLLPath)
========== TARGET SITE ==========
System.Reflection.RuntimeAssembly nLoadFile(System.String, System.Security.Policy.Evidence)

========== DISPATCHER ==========
Thread Name: 
Is ThreadPool Thread: False

I see something with .net framework, but the link provided does not really do a good job of explaining what config you need to change stuff in or where it is.

**Comment by BakaBox** [comment]
See if Issue #13 will fix it.

**Comment by folence** [comment]
Thanks, that fixed the problem, it works great as far as I can tell :)
